### PR TITLE
Code Refactoring

### PR DESCRIPTION
**Pull request by MoMMde**
# Code refactoring
I just made the code smaller & moved to bukkit plugin acces

- [ ] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the SiegeWar [License](https://github.com/TownyAdvanced/SiegeWar/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

**Comment by Goosius1** [comment]
- Ok cool, looks nice
- Did you test this on a local server?

**Comment by Goosius1** [comment]
- I'm doing a release shortly
- Since this code looks good to me, and since I will be testing the version before release now, I will merge

**Comment by Goosius1** [comment]
- Oh one more thing, I've added the licence information to the PR description.
- Can you confirm with a comment you are ok with the licence?, then I will merge

**Comment by Goosius1** [comment]
- Tell you what, these improvements looks good to me, but lets keep them for 0.2.0 just to be safe.
- Normally after we do pre-releases, we leave a few days to make sure changes are ok.
- Given that today we're doing the first full release, I'm reluctant to put in anything except bugfixes.

**Comment by MoMMde** [comment]
+ I dont have any problem with the Licence 👍🏻 
+ I sadly can't test it at the moment. Maybe i will send an update comment later

**Comment by Goosius1** [comment]
- That's ok, we're not in a rush now.
- So, the usual process is that the person who does the PR will test their changes on a local server (*and tick the box*).
- Do you have a local server where you can do that?

**Review by Goosius1 — CHANGES_REQUESTED** [review]
- Code looks good
- No code changes requested, but a test of the code on a local server is requested.

**Comment by Goosius1** [comment]
Hi, can you test this?

**Comment by Goosius1** [comment]
- PR closed as no response from PR opener.
- If this work is still active then get in touch with us on the TownyAdvanced discord, and I'm sure we can re-open it and figure out what to do next
  - Depending on how long it is until you pick it up again, there may be merge conflicts.
  - After those are resolved it will need game-testing in the areas effected.
  - Usually this is done on a local server belonging to the PR-opener.
  - But if there's any issue with that, send us a test plan and we might have capacity to do it for you.

**Pull request closed without merging**
